AllCops:
  RubyInterpreters:
    - ruby


Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 12

Metrics/AbcSize: 
  Max: 35

Metrics/BlockLength:
  Max: 30
